server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    client_01: /client_01/*
    client_02: /client_02/*
spring:
  application:
    name: gateway