server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hystrix
#结合feign熔断
feign:
  hystrix:
    enabled: true
#数据监控
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'